apiVersion: v1
kind: Service
metadata:
  labels:
    name: articulate
  name: articulate
spec:
  ports:
    - port: 80		# This is the port we will access the app on
      targetPort: 8080	# This is the port the app listens on
  selector:
    app: articulate
  type: LoadBalancer	# If deploying to NSX-T
#  type: NodePort	# If NSX-T is not installed

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: articulate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: articulate
    spec:
      containers:
      - name: articulate
        image: harbor.haas-109.pez.pivotal.io/library/articulate:latest
        ports:
        - containerPort: 8080	# This is the port the app listens on
